In [2]:
import numpy as np
data = np.array([[1,0,4],[2,2,0],[0,0,5]])
eig_value, eig_vector = np.linalg.eig(data.dot(data.T))
eig_value = np.sort(eig_value)[::1]
print('特征值：',eig_value)
print('特征值的平方根:',np.sqrt(eig_value))

特征值： [ 0.29198263  8.26378188 41.44423549]
特征值的平方根: [0.54035417 2.87467944 6.43771974]


In [5]:
U,S,V = np.linalg.svd(data)
recon_data = np.round(U[:,:2].dot(np.diag(S[:2])).dot(V[:2,:]),0).astype(int)
print('奇异值',S)
print(data)
print(recon_data)

奇异值 [6.43771974 2.87467944 0.54035417]
[[1 0 4]
 [2 2 0]
 [0 0 5]]
[[1 0 4]
 [2 2 0]
 [0 0 5]]


In [6]:
import numpy as np
eig_val, u_vec = np.linalg.eig(data.dot(data.T))
s_val = np.sqrt(eig_val)
s_val_sort_idx = np.argsort(s_val)[::-1]
u_vec = u_vec[:,s_val_sort_idx]
s_val = np.sort(s_val)[::-1]
s_val_inv = np.linalg.inv(np.diag(s_val))
v_vec = s_val_inv.dot((u_vec.T).dot(data))
reco_data = np.round(u_vec[:,:2].dot(np.diag(s_val[:2])).dot(v_vec[:2,:]),0).astype(int)
print('左奇异矩阵',u_vec)
print('奇异值',s_val)
print('左奇异矩阵V:',v_vec)
print('data',data)
print('U*S*V',reco_data)

左奇异矩阵 [[ 0.63464303 -0.12919086  0.76193041]
 [ 0.03795231 -0.97952798 -0.19769816]
 [ 0.77187295  0.15438478 -0.61674751]]
奇异值 [6.43771974 2.87467944 0.54035417]
左奇异矩阵V: [[ 0.11037257  0.01179061  0.99382034]
 [-0.72642772 -0.68148675  0.08876135]
 [ 0.67832195 -0.73173546 -0.06665242]]
data [[1 0 4]
 [2 2 0]
 [0 0 5]]
U*S*V [[1 0 4]
 [2 2 0]
 [0 0 5]]


In [8]:
path = '1c_r.jpg'
data = io.imread(path,as_gray=True)
print(data.shape)
U,sigma,VT = np.linalg.svd(data)
count = 30
dig = np.diag(sigma[:count])
redata = U[:,:count]*dig*VT[:count,:]
plt.imshow(data,cmap='gray')
plt.title('原始图片')
plt.show()
plt.imshow(redata,cmap='gray')
plt.title('基于SVD压缩重构后的图片')
plt.show()

In [9]:
import numpy as np
data_1 = np.array([1,2,3])
print('输入是1维数组时的结果',np.diag(data_1))


输入是1维数组时的结果 [[1 0 0]
 [0 2 0]
 [0 0 3]]


In [10]:
data_2 = np.array([[1,0,4],[2,2,0],[0,0,5]])
print(np.diag(data_2))

[1 2 5]
