In [2]:
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [4]:
np.linspace(1,5,11)


array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [6]:
np.arange(1,5,2)

array([1, 3])

In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [11]:
np.full((2,3),[1,2,3])

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
np.random.rand(3)

array([0.9015341 , 0.01681719, 0.00669661])

In [15]:
np.random.randint(10)

6

In [16]:
np.random.randn(4)

array([-0.65652513,  0.61704332,  0.50830247, -0.36306387])

In [18]:
np.random.randint(10)

2

In [20]:
a,b = 5,15
(b-a) * np.random.rand(3)+a

array([11.03867976, 13.63925711,  9.39557767])

In [22]:
np.random.uniform(5,15,3)

array([10.66659799,  6.46570091,  7.53276761])

In [24]:
np.random.randn(3)

array([0.54817352, 0.32439638, 0.25006843])

In [26]:
np.random.randn(2,2)

array([[ 1.73544917, -1.23415076],
       [ 1.70827318,  1.6862894 ]])

In [28]:
sigma,mu = 2.5,3
mu + np.random.randn(3)*sigma

array([6.21422329, 3.78968928, 7.65175454])

In [30]:
np.random.normal(3,2.5,3)

array([1.50225667, 3.39129787, 3.52764542])

In [32]:
low,high,size = 5,15,(2,2)
np.random.randint(low,high,size)

array([[11,  9],
       [ 7,  8]])

In [34]:
my_list = ['a','b','c','d']
np.random.choice(my_list,2,replace=False,p=[0.1,0.7,0.1,0.1])


array(['b', 'd'], dtype='<U1')

In [36]:
np.random.choice(my_list,(3,3))

array([['d', 'a', 'b'],
       ['b', 'a', 'c'],
       ['b', 'b', 'c']], dtype='<U1')

In [38]:
np.random.permutation(my_list)

array(['d', 'b', 'a', 'c'], dtype='<U1')

In [45]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [46]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [47]:
np.zeros((3,2)).T

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.r_[np.zeros((2,3)),np.zeros((2,3))]


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [51]:
np.c_[np.zeros((2,3)),np.zeros((2,3))]

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [53]:
try:
    np.r_[np.array([0,0]),np.zeros((2,1))]
except Exception as e:
    Err_Msg = e
    

In [55]:
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [56]:
np.r_[np.array([0,0]),np.zeros(2)]


array([0., 0., 0., 0.])

In [58]:
np.c_[np.array([0,0]),np.zeros((2,3))]

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [60]:
target = np.arange(8).reshape(2,4)
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [61]:
target.reshape((4,2),order='C')


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [62]:
target.reshape((4,2),order='F')

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [63]:
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [65]:
target.reshape((1,-1))

array([[0, 1, 2, 3, 4, 5, 6, 7]])

In [67]:
target = np.ones((3,1))
target.reshape(-1)

array([1., 1., 1.])

In [68]:
target = np.arange(9).reshape(3,3)

In [70]:
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
target[:-1,[0,2]]

array([[0, 2],
       [3, 5]])

In [72]:
target[np.ix_([True,False,True],[True,False,True])]


array([[0, 2],
       [6, 8]])

In [73]:
target[np.ix_([1,2],[True,False,True])]

array([[3, 5],
       [6, 8]])

In [75]:
new = target.reshape(-1)

In [77]:
new

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
a = np.array([-1,1,-1,0])
np.where(a>0,a,5)

array([5, 1, 5, 5])

In [81]:
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5]),)

In [82]:
a.argmax()

4

In [83]:
a.argmin()

1

In [84]:
a = np.array([0,1])
a.any(),a.all()

(True, False)

In [85]:
a = np.array([1,2,3])
a.cumprod()

array([1, 2, 6])

In [86]:
a.cumsum()

array([1, 3, 6])

In [87]:
np.diff(a)

array([1, 1])

In [88]:
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [90]:
target.max(),target.min(),target.mean(),target.std(),target.var(),target.sum()

(4, 0, 2.0, 1.4142135623730951, 2.0, 10)

In [91]:
np.median(target)

2.0

In [92]:
np.quantile(target,0.5)

2.0

In [93]:
target = np.array([1,2,np.nan])

In [94]:
target

array([ 1.,  2., nan])

In [95]:
target.max()

nan

In [96]:
np.nanmax(target)

2.0

In [97]:
np.nanquantile(target,0.5)

1.5

In [98]:
target1 = np.array([1,3,5,9])

In [99]:
target2 = np.array([1,5,3,-9])


In [100]:
np.cov(target1,target2)


array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [101]:
np.corrcoef(target1,target2)

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [104]:
target = np.arange(1,10).reshape(3,-1)
print(target)
target.sum(1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [105]:
res = 3*np.ones((2,2))+1
res

array([[4., 4.],
       [4., 4.]])

In [106]:
res = 1/res

In [107]:
res

array([[0.25, 0.25],
       [0.25, 0.25]])

In [108]:
np.ones(3),np.ones((2,3))

(array([1., 1., 1.]),
 array([[1., 1., 1.],
        [1., 1., 1.]]))

In [109]:
np.ones(3)+np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [110]:
np.ones(3),np.ones((2,1))

(array([1., 1., 1.]),
 array([[1.],
        [1.]]))

In [111]:
np.ones(3)+np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])