In [1]:
import numpy as np

np.array([1,1,2])

array([1, 1, 2])

In [2]:
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [3]:
import time
time.time()
type(time.time())

float

In [2]:
import numpy as np
my_array = np.array([1,2,3,4,5])
print(my_array)

[1 2 3 4 5]


In [4]:
print(my_array.shape)

(5,)


In [6]:
print(my_array[0],my_array[1])

1 2


In [8]:
my_array[0]=-1
print(my_array)

[-1  2  3  4  5]


In [10]:
my_new_array = np.zeros((5))
my_new_array

array([0., 0., 0., 0., 0.])

In [11]:
my_random_array= np.random.random((5))

In [12]:
print(my_random_array)

[0.24466    0.34037051 0.92865529 0.17299191 0.94361376]


In [14]:
my_2d = np.zeros((2,3))
my_2d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
my_2d_array = np.ones((2,4))
print(my_2d_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
my_2d[1][1]

0.0

In [18]:
my_array = np.array([[4,5],[6,1]])
print(my_array)

[[4 5]
 [6 1]]


In [19]:
import pandas as pd

In [24]:
def createDataSet():
    dataSet = [[1,1,'yes'],
              [1,1,'yes'],
              [1,1,'no'],
              [1,1,'no'],
               [1,1,'no']]
    label= ['no surfacing','filppers']
    return dataSet,label

if __name__ == '__main__':
    dataSet,labels = createDataSet()
    print(dataSet)
    print(labels)

[[1, 1, 'yes'], [1, 1, 'yes'], [1, 1, 'no'], [1, 1, 'no'], [1, 1, 'no']]
['no surfacing', 'filppers']


In [25]:
from math import log
def calcShannonEnt(dataSet):
    numEntries = len(dataSet)
    labelCounts = {}
    for featVec in dataSet:
        currentLabel = featVec[-1]
        if currentLabel not in labelCounts.keys():
            labelCounts[currentLabel]=0
        labelCounts[currentLabel]+=1
    shannonEnt = 0.0
    for key in labelCounts:
        prob = float(labelCounts[key])/numEntries
        shannonEnt -= prob * log(prob,2)
    return shannonEnt

In [26]:
if __name__ == '__main__':
    H = calcShannonEnt(dataSet)
    print(H)

0.9709505944546686


In [27]:
def splitDateSet(dataSet,axis,value):
    retDataSet = []
    for featVec in dataSet:
        if featVec[axis]==value:
            reducedFeatVec = featVec[:,axis]
            reducedFeatVec.extend(featVec[axis+1,:])
            retDataSet.append(reducedFeatVec)
    return retDataSet

In [ ]:
def chooseBestFeatureToSplit(dataSet):
    numFeatures = len(dataSet[0])-1
    baseEntropy = calcShannonEnt(dataSet)
    bestInfoGain = 0.0
    bestFeature = -1
    for i in range(numFeatures):
        featList = [example[i] for example in dataSet]
        uniqueVals = set(featList)
        netEntropy = 0.0
        for value in uniqueVals:
            subDataSet = splitDateSet(dataSet,i,valuelue)
            prob = len(s)