In [22]:
meeting = {}
nums = int(input())
for i in range(nums):
    n = int(input())
    list_n  = []
    for j in range(n):
        info_time = input()
        a,b = int(info_time.split(' ')[0]),int(info_time.split(' ')[1])
        list_n.append([a,b])
    meeting[i] = list_n

for i in meeting.keys():
    data = meeting[i]
    data = sorted(data,key = lambda x: (x[0],x[1]))
    start = data[0][0]
    end = data[1][1]
    result  = end - start
    for j in data[1:]:
        if j[0]>end:
            start = j[0]
            end = j[1]
            result  += (end - start) 
    print(result)

1
2
1 2
2 3
2


In [23]:
L = [(12,12),(13,13),(14,12),(12,34),(13,22),(13,64)]
L.sort(key=lambda x:(x[0],-x[1]))

In [26]:
from sklearn.feature_extraction.text import CountVectorizer
verctor = CountVectorizer()
res = verctor.fit_transform(['lift is short i love python','lift is too long,I have python'])
print(res.toarray())

[[0 1 1 0 1 1 1 0]
 [1 1 1 1 0 1 0 1]]


In [28]:
from sklearn.feature_extraction import DictVectorizer
alist = [{'city':'Beijing','temp':33},
         {'city':'GZ','temp':42},
         {'city':'SH','temp':40}]
d = DictVectorizer()
feature = d.fit_transform(alist)

In [31]:
print(feature)

  (0, 0)	1.0
  (0, 3)	33.0
  (1, 1)	1.0
  (1, 3)	42.0
  (2, 2)	1.0
  (2, 3)	40.0


In [34]:
from sklearn.feature_extraction import DictVectorizer
alist = [{'city':'Beijing','temp':33},
         {'city':'GZ','temp':42},
         {'city':'SH','temp':40}]
d = DictVectorizer(sparse=False)
feature = d.fit_transform(alist)
print(feature)
print(d.get_feature_names())

[[ 1.  0.  0. 33.]
 [ 0.  1.  0. 42.]
 [ 0.  0.  1. 40.]]
['city=Beijing', 'city=GZ', 'city=SH', 'temp']


In [37]:
import pandas as pd
df = pd.DataFrame([
    ['green','M',20,'class1'],
    ['red','L',21,'class2'],
    ['blue','XL',30,'class3'],
])
df.columns=['color','size','weight','class Label']

In [39]:
df


color size  weight class Label
0  green    M      20      class1
1    red    L      21      class2
2   blue   XL      30      class3

In [40]:
pd.get_dummies(df['color'])

blue  green  red
0     0      1    0
1     0      0    1
2     1      0    0

In [42]:
from sklearn.feature_extraction import DictVectorizer
alist = [{'city':'Beijing','temp':33},
         {'city':'GZ','temp':42},
         {'city':'SH','temp':40}]
d = DictVectorizer(sparse=False)
feature = d.fit_transform(alist)
print(feature)
print(d.get_feature_names())

[[ 1.  0.  0. 33.]
 [ 0.  1.  0. 42.]
 [ 0.  0.  1. 40.]]
['city=Beijing', 'city=GZ', 'city=SH', 'temp']


In [43]:
from sklearn.feature_extraction.text import CountVectorizer
vector = CountVectorizer()
res = vector.fit_transform(['lift is short, I love python','left is too long,I have python'])
print(res)

  (0, 3)	1
  (0, 1)	1
  (0, 7)	1
  (0, 5)	1
  (0, 6)	1
  (1, 1)	1
  (1, 6)	1
  (1, 2)	1
  (1, 8)	1
  (1, 4)	1
  (1, 0)	1


In [45]:
res.toarray()

array([[0, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 1, 1, 0, 1, 0, 1, 0, 1]])

In [47]:
print(vector.get_feature_names())

['have', 'is', 'left', 'lift', 'long', 'love', 'python', 'short', 'too']


In [49]:
res_cn = vector.fit_transform(['人生苦短，我用Python','人生漫长，不用python'])
print(res_cn)

  (0, 2)	1
  (0, 3)	1
  (1, 1)	1
  (1, 0)	1


In [53]:
print(vector.get_feature_names())
print(res_cn.toarray())

['不用python', '人生漫长', '人生苦短', '我用python']
[[0 0 1 1]
 [1 1 0 0]]


In [55]:
import jieba
jb = jieba.cut('我是一个好人')
content = list(jb)
print(content)

['我', '是', '一个', '好人']


In [57]:
ct = ' '.join(content)
ct

'我 是 一个 好人'

In [62]:
jb1 = jieba.cut('人生苦短，我用Python，你觉得我说的对吗？')
ct1 = ' '.join(list(jb1))
jb2 = jieba.cut('人生苦短，我用Python，你觉得我说的对不对？')
ct2 = ' '.join(list(jb2))

In [63]:
print(ct1,ct2)

人生 苦短 ， 我用 Python ， 你 觉得 我 说 的 对 吗 ？ 人生 苦短 ， 我用 Python ， 你 觉得 我 说 的 对 不 对 ？


In [64]:
from sklearn.feature_extraction.text import CountVectorizer
verctor = CountVectorizer()
res = verctor.fit_transform([ct1,ct2])
print(res)
print(verctor.get_feature_names())
print(res.toarray())

  (0, 1)	1
  (0, 3)	1
  (0, 2)	1
  (0, 0)	1
  (0, 4)	1
  (1, 1)	1
  (1, 3)	1
  (1, 2)	1
  (1, 0)	1
  (1, 4)	1
['python', '人生', '我用', '苦短', '觉得']
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [67]:
from sklearn.preprocessing import MinMaxScaler
mm = MinMaxScaler(feature_range=(0,1))
data = [[90,2,10,4],[60,5,15,45],[73,3,13,45]]
data = mm.fit_transform(data)
data

array([[1.        , 0.        , 0.        , 0.        ],
       [0.        , 1.        , 1.        , 1.        ],
       [0.43333333, 0.33333333, 0.6       , 1.        ]])

In [69]:
from sklearn.preprocessing import StandardScaler
mm = StandardScaler()
data = [[90,2,10,4],[60,5,15,45],[73,3,13,45]]
data = mm.fit_transform(data)
data

array([[ 1.27540458, -1.06904497, -1.29777137, -1.41421356],
       [-1.16685951,  1.33630621,  1.13554995,  0.70710678],
       [-0.10854507, -0.26726124,  0.16222142,  0.70710678]])

In [71]:
from sklearn.feature_selection import VarianceThreshold
v = VarianceThreshold(threshold=3)
v.fit_transform([[0,2,4,3],[0,3,7,3],[0,9,6,3]])

array([[2],
       [3],
       [9]])

In [72]:
import numpy as np
feature = np.random.randint(0,100,size=(5,10))
feature

array([[97, 12, 67, 51, 78, 39, 96, 14, 36, 68],
       [13, 62, 20, 23, 49, 67, 14, 91, 44, 44],
       [98, 60, 91, 86, 86, 92, 57, 71, 66, 39],
       [73, 65, 64, 40, 60, 62, 49, 77,  3, 77],
       [53, 55, 80, 57, 71, 52, 12, 46, 17, 22]])

In [76]:
mean = np.median(feature.var(axis=0))

In [78]:
v = VarianceThreshold(threshold=mean)
v.fit_transform(feature)

array([[97, 67, 96, 14, 36],
       [13, 20, 14, 91, 44],
       [98, 91, 57, 71, 66],
       [73, 64, 49, 77,  3],
       [53, 80, 12, 46, 17]])

In [81]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
pca.fit_transform([[0,2,4,3],[0,3,7,3],[0,9,6,4]])

array([[-2.89907883e+00, -1.26306846e+00,  1.34020526e-16],
       [-1.48739895e+00,  1.56662409e+00,  1.34020526e-16],
       [ 4.38647778e+00, -3.03555627e-01,  1.34020526e-16]])

In [83]:
pca.explained_variance_

array([1.49291005e+01, 2.07089949e+00, 2.69422521e-32])

In [85]:
pca.explained_variance_ratio_

array([8.78182383e-01, 1.21817617e-01, 1.58483836e-33])

In [87]:
pca.get_covariance()

array([[ 1.93371683e-31, -1.63741677e-15, -1.25698241e-16,
        -2.51923793e-16],
       [-1.63741677e-15,  1.43333333e+01,  1.83333333e+00,
         2.16666667e+00],
       [-1.25698241e-16,  1.83333333e+00,  2.33333333e+00,
         1.66666667e-01],
       [-2.51923793e-16,  2.16666667e+00,  1.66666667e-01,
         3.33333333e-01]])

In [89]:
import sklearn.datasets as datasets
iris =datasets.load_iris()

In [91]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [92]:
feature = iris['data']
target = iris['target']

In [93]:
feature.shape,target.shape

((150, 4), (150,))

In [ ]:
datasets.fetch_20newsgroups(data_home=None,subset='all')

In [94]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(feature,target,test_size=0.2,random_state=30)