In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [4]:
output = [np.argwhere(np.unique(species_small)==s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [5]:
output = []
uniqs = np.unique(species_small)
for val in uniqs:
    for s in species_small[species_small==val]:
        groupid = np.argwhere(uniqs==s).tolist()[0][0]
        output.append(groupid)

In [7]:
output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [8]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [10]:
np.random.seed(100)
a = np.random.randint(1,10,[5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [13]:
np.max(a,axis=1)

array([9, 8, 6, 3, 9])

In [14]:
np.amax(a,axis=1)

array([9, 8, 6, 3, 9])

In [15]:
np.apply_along_axis(np.max,arr=a,axis=1)

array([9, 8, 6, 3, 9])

In [16]:
np.apply_along_axis(lambda x : np.min(x)/np.max(x),arr=a,axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [18]:
np.random.seed(100)
a = np.random.randint(0,5,10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [21]:
np.unique(a,return_index=True)[1]

array([0, 4, 2, 5])

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [23]:
numeric_column = iris[:,1].astype('float')
grouping_column = iris[:,4]


In [25]:
[[group_val,numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]


[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)

In [28]:
dist

6.708203932499369

In [30]:
a = np.array([1,3,7,1,2,6,0,1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff==-2)[0]+1
peak_locations

array([2, 5])

In [33]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
a_2d - b_1d[:,None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
a_2d - b_1d.reshape(3,-1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [38]:
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
n = 5
[i for i,v in enumerate(x) if v==1][n-1]

8

In [39]:
np.where(x==1)[0][n-1]

8

In [40]:
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n

In [41]:
np.random.seed(100)
Z = np.random.randint(10,size=10)
print(Z)
moving_average(Z,n=3).round(2)

[8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [44]:
datas = np.arange(np.datetime64('2018-02-01'),np.datetime64('2018-02-25'),2)
datas

array(['2018-02-01', '2018-02-03', '2018-02-05', '2018-02-07',
       '2018-02-09', '2018-02-11', '2018-02-13', '2018-02-15',
       '2018-02-17', '2018-02-19', '2018-02-21', '2018-02-23'],
      dtype='datetime64[D]')

In [46]:
fill_ind = np.array([np.arange(date,(date+d)) for date,d in zip(datas,np.diff(datas))]).reshape(-1)
fill_ind

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22'], dtype='datetime64[D]')

In [64]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
start = 0
length = 4
step = 2
a = [[arr[i*step:i*step+length] for i in range(len(arr)//step-1)]]
print(np.concatenate(a))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [88]:
def gen_stride(a,stride_len=5,window_len=5):
    n_strides = ((a.size-window_len)//stride_len)+1
    return np.array([a[s:(s+window_len)] for s in np.arange(0,n_strides*stride_len,stride_len)])
print(gen_stride(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [2]:
import pandas as pd
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data',header=None)
df.head()

0  1      2      3       4       5        6        7       8   \
0    842302  M  17.99  10.38  122.80  1001.0  0.11840  0.27760  0.3001   
1    842517  M  20.57  17.77  132.90  1326.0  0.08474  0.07864  0.0869   
2  84300903  M  19.69  21.25  130.00  1203.0  0.10960  0.15990  0.1974   
3  84348301  M  11.42  20.38   77.58   386.1  0.14250  0.28390  0.2414   
4  84358402  M  20.29  14.34  135.10  1297.0  0.10030  0.13280  0.1980   

        9   ...     22     23      24      25      26      27      28      29  \
0  0.14710  ...  25.38  17.33  184.60  2019.0  0.1622  0.6656  0.7119  0.2654   
1  0.07017  ...  24.99  23.41  158.80  1956.0  0.1238  0.1866  0.2416  0.1860   
2  0.12790  ...  23.57  25.53  152.50  1709.0  0.1444  0.4245  0.4504  0.2430   
3  0.10520  ...  14.91  26.50   98.87   567.7  0.2098  0.8663  0.6869  0.2575   
4  0.10430  ...  22.54  16.67  152.20  1575.0  0.1374  0.2050  0.4000  0.1625   

       30       31  
0  0.4601  0.11890  
1  0.2750  0.08902  
2  0.3613  0.08758  
3  0.6638  0.17300  
4  0.2364  0.07678  

[5 rows x 32 columns]

In [3]:
X = df.loc[:,2:].values
y = df.loc[:,1].values
from sklearn.preprocessing import LabelEncoder

In [4]:
le = LabelEncoder()
y = le.fit_transform(y)


In [7]:
pd.value_counts(y)

0    357
1    212
dtype: int64

In [9]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)


In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe_lr = Pipeline([('scl',StandardScaler()),('pca',PCA(n_components=2)),('clf',LogisticRegression(random_state=1))])
pipe_lr.fit(X_train,y_train)
print('Test Accuracy:%.3f'%pipe_lr.score(X_test,y_test))

Test Accuracy:0.947


In [17]:
!pip3 install pydot

In [28]:
from io import StringIO
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
import pydot
for criention in ['gini','entropy']:
    clf = DecisionTreeClassifier(criterion=criention,random_state=0,max_depth=3)
    iris = load_iris()
    dot_data = StringIO()
    clf.fit(iris.data,iris.target)
    print(clf.feature_importances_)
    tree.export_graphviz(clf,out_file=dot_data)
    graph = pydot.graph_from_dot_data(dot_data.getvalue())

[0.         0.         0.05393633 0.94606367]
[0.         0.         0.07060267 0.92939733]


In [39]:
from datetime import datetime
print(datetime.now())
print(type(datetime.now()))

2021-08-19 09:25:34.773650
<class 'datetime.datetime'>


In [44]:
import datetime
now_month = datetime.date(datetime.date.today().year,datetime.date.today().month,1)
print(now_month)
print((datetime.date.today().replace(day=1)-datetime.timedelta(days=1)).replace(day=1))

2021-08-01
2021-07-01


In [51]:
now = datetime.date.today()
print(now)
print(now.weekday())
print(now-datetime.timedelta(now.weekday()))
print(now+datetime.timedelta(now.weekday()))

2021-08-19
3
2021-08-16
2021-08-22
