In [2]:
import numpy as np
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
species_small

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica'], dtype='<U15')

In [4]:
output = [np.argwhere(np.unique(species_small)==s).tolist()[0][0] for val in np.unique(species_small) for s in species_small[species_small==val]]
output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [5]:
output = []
uniqs = np.unique(species_small)
for val in uniqs:
    for s in species_small[species_small==val]:
        groupid = np.argwhere(uniqs==s).tolist()[0][0]
        output.append(groupid)

In [7]:
output

[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [8]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


In [10]:
np.random.seed(100)
a = np.random.randint(1,10,[5,3])
a

array([[9, 9, 4],
       [8, 8, 1],
       [5, 3, 6],
       [3, 3, 3],
       [2, 1, 9]])

In [13]:
np.max(a,axis=1)

array([9, 8, 6, 3, 9])

In [14]:
np.amax(a,axis=1)

array([9, 8, 6, 3, 9])

In [15]:
np.apply_along_axis(np.max,arr=a,axis=1)

array([9, 8, 6, 3, 9])

In [16]:
np.apply_along_axis(lambda x : np.min(x)/np.max(x),arr=a,axis=1)

array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [18]:
np.random.seed(100)
a = np.random.randint(0,5,10)
a

array([0, 0, 3, 0, 2, 4, 2, 2, 2, 2])

In [21]:
np.unique(a,return_index=True)[1]

array([0, 4, 2, 5])

In [22]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [23]:
numeric_column = iris[:,1].astype('float')
grouping_column = iris[:,4]


In [25]:
[[group_val,numeric_column[grouping_column==group_val].mean()] for group_val in np.unique(grouping_column)]


[[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.7700000000000005],
 [b'Iris-virginica', 2.974]]

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)

In [28]:
dist

6.708203932499369

In [30]:
a = np.array([1,3,7,1,2,6,0,1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff==-2)[0]+1
peak_locations

array([2, 5])

In [33]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]])
b_1d = np.array([1,2,3])
a_2d - b_1d[:,None]

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [36]:
a_2d - b_1d.reshape(3,-1)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [38]:
x = np.array([1,2,1,1,3,4,3,1,1,2,1,1,2])
n = 5
[i for i,v in enumerate(x) if v==1][n-1]

8

In [39]:
np.where(x==1)[0][n-1]

8

In [40]:
def moving_average(a,n=3):
    ret = np.cumsum(a,dtype=float)
    ret[n:]=ret[n:]-ret[:-n]
    return ret[n-1:]/n

In [41]:
np.random.seed(100)
Z = np.random.randint(10,size=10)
print(Z)
moving_average(Z,n=3).round(2)

[8 8 3 7 7 0 4 2 5 2]


array([6.33, 6.  , 5.67, 4.67, 3.67, 2.  , 3.67, 3.  ])

In [44]:
datas = np.arange(np.datetime64('2018-02-01'),np.datetime64('2018-02-25'),2)
datas

array(['2018-02-01', '2018-02-03', '2018-02-05', '2018-02-07',
       '2018-02-09', '2018-02-11', '2018-02-13', '2018-02-15',
       '2018-02-17', '2018-02-19', '2018-02-21', '2018-02-23'],
      dtype='datetime64[D]')

In [46]:
fill_ind = np.array([np.arange(date,(date+d)) for date,d in zip(datas,np.diff(datas))]).reshape(-1)
fill_ind

array(['2018-02-01', '2018-02-02', '2018-02-03', '2018-02-04',
       '2018-02-05', '2018-02-06', '2018-02-07', '2018-02-08',
       '2018-02-09', '2018-02-10', '2018-02-11', '2018-02-12',
       '2018-02-13', '2018-02-14', '2018-02-15', '2018-02-16',
       '2018-02-17', '2018-02-18', '2018-02-19', '2018-02-20',
       '2018-02-21', '2018-02-22'], dtype='datetime64[D]')

In [64]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [87]:
start = 0
length = 4
step = 2
a = [[arr[i*step:i*step+length] for i in range(len(arr)//step-1)]]
print(np.concatenate(a))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]


In [86]:
def gen_stride(a,stride_len=5,window_len=5):
    n_strides = ((a.size-window_len)//stride_len)+1
    return np.array([a[s:(s+window_len)] for s in np.arange(0,n_strides*stride_len,stride_len)])
print(gen_stride(np.arange(15), stride_len=2, window_len=4))

[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
