In [2]:
import numpy as np
print(np.__version__)

1.20.3


In [4]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [5]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [12]:
arr_1 = np.arange(10)
arr_1[arr_1%2==1]=-1
arr_1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr = np.arange(10)
out = np.where(arr%2==1,-1,arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack([a,b]),np.concatenate([a,b],axis=0),np.r_[a,b]

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [25]:
np.hstack([a,b]),np.concatenate([a,b],axis=1),np.c_[a,b]

(array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]))

In [28]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
a = np.array([1,2,3,4,5,6,6,7,8,9,9])
b = np.array([7,2,10,2,7,4,9,8])
c = np.intersect1d(a,b)


In [35]:
np.setdiff1d(a,c)

array([1, 3, 5, 6])

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,10])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [46]:
index = np.where((a>=5)&(a<=10))
a[index]

array([5, 6])

In [49]:
index = np.where(np.logical_and(a>=5,a<=10))
a[index]

array([5, 6])

In [51]:
a[(a>=5)&(a<=10)]

array([5, 6])

In [54]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
    
a = np.arange(1,10,2)
b = np.arange(1,20,4)
print(a,b)
pair_max = np.vectorize(maxx,otypes=[float])
pair_max(a,b)


[1 3 5 7 9] [ 1  5  9 13 17]


array([ 1.,  5.,  9., 13., 17.])

In [57]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [64]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [67]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [70]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [77]:
np.random.randint(5,10,size=(5,3))+np.random.random((5,3))

array([[7.28710235, 7.56420456, 8.81275296],
       [8.60435264, 8.29209066, 8.80332706],
       [6.9996048 , 8.43685478, 7.44228248],
       [5.4458943 , 6.88663173, 6.24665371],
       [7.17839238, 9.25552805, 6.39575558]])

In [79]:
np.random.uniform(5,10,size=(5,3))


array([[7.19938273, 7.43763482, 9.93625887],
       [6.19699866, 6.51983942, 7.34547726],
       [8.36369635, 9.63285827, 9.24602833],
       [7.63254336, 7.55596454, 7.21924369],
       [7.2711361 , 5.78280897, 5.61187528]])

In [81]:
np.set_printoptions(precision=3)
np.random.uniform(5,10,size=(5,3))

array([[5.205, 5.781, 6.613],
       [7.072, 8.848, 6.762],
       [8.62 , 7.712, 5.929],
       [7.385, 5.397, 7.514],
       [8.179, 9.11 , 5.788]])

In [82]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [84]:
rand_arr

array([[5.434e-04, 2.784e-04, 4.245e-04],
       [8.448e-04, 4.719e-06, 1.216e-04],
       [6.707e-04, 8.259e-04, 1.367e-04]])

In [86]:
np.set_printoptions(suppress=True,precision=6)
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [87]:
np.set_printoptions(threshold=6)
np.arange(100)

array([ 0,  1,  2, ..., 97, 98, 99])

In [94]:
import sys
np.set_printoptions(threshold=sys.maxsize)
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',',dtype='object')
names=('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [97]:
iris_1d = np.genfromtxt(url,delimiter=',',dtype=None)
iris_1d[:2]

/Users/yanshuo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  """Entry point for launching an IPython kernel.


array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa')],
      dtype=[('f0', '<f8'), ('f1', '<f8'), ('f2', '<f8'), ('f3', '<f8'), ('f4', 'S15')])

In [100]:
np.set_printoptions(threshold=6)
np.array([row[4] for row in iris_1d])

array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S15')

In [102]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url,delimiter=',',dtype=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d[:4]

/Users/yanshuo/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [107]:
sepallength = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])

In [109]:
np.mean(sepallength),np.std(sepallength),np.median(sepallength)

(5.843333333333334, 0.8253012917851409, 5.8)

In [113]:
max_s = sepallength.max()
min_s = sepallength.min()
S = (sepallength-min_s)/(max_s-min_s)
S

array([0.222222, 0.166667, 0.111111, ..., 0.611111, 0.527778, 0.444444])

In [116]:
S = (sepallength-min_s)/sepallength.ptp()
S

array([0.222222, 0.166667, 0.111111, ..., 0.611111, 0.527778, 0.444444])

In [119]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url,delimiter=',',dtype='object')
sepallength = np.array([float(row[0]) for row in iris])
def softmax(x):
    ex = np.exp(x-np.max(x))
    return ex/ex.sum(axis=0)
print(softmax(sepallength))

[0.00222  0.001817 0.001488 ... 0.009001 0.006668 0.00494 ]


In [121]:
sepallength = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])


In [123]:
np.percentile(sepallength,q=[5,95])

array([4.6  , 7.255])

In [125]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='object')
iris_2d[:2]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

In [129]:
i,j = np.where(iris_2d)

In [133]:
np.random.seed(100)
iris[np.random.randint(150,size=20),np.random.randint(4,size=20)]=np.nan

In [149]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
np.random.seed(100)
iris_2d[np.random.randint(150,size=20),np.random.randint(4,size=20)] = np.nan
print(np.isnan(iris_2d[:,0]).sum())
print(np.where(np.isnan(iris_2d[:,0])))

4
(array([14, 34, 79, 87]),)


In [150]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan


In [152]:
any_none = np.array([~np.any(np.isnan(row)) for row in iris_2d])
iris_2d[any_none][:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [154]:
iris_2d[np.sum(np.isnan(iris_2d),axis=1)==0][:4]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [156]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])

np.corrcoef(iris_2d[:,0],iris_2d[:,2])

array([[1.      , 0.871754],
       [0.871754, 1.      ]])

In [158]:
from scipy.stats.stats import pearsonr
corr,p_value = pearsonr(iris_2d[:,0],iris_2d[:,2])
print(corr)

0.8717541573048713


In [160]:
from scipy.stats.stats import pearsonr
corr,p_vlaue = pearsonr(iris_2d[:,0],iris_2d[:,2])
corr,p_value

(0.8717541573048713, 1.0384540627941062e-47)

In [169]:
a = list(range(100))
a = sorted(a)
len_a = len(a)
a[int(len_a/100*10)]


10

In [173]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan
np.isnan(iris_2d).sum()

20

In [175]:
iris_2d[np.isnan(iris_2d)]=0

In [178]:
species = np.genfromtxt(url,delimiter=',',dtype='object',usecols=[4])
np.unique(species,return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object),
 array([50, 50, 50]))

In [183]:
petallength = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[2])
bins = [0,3,5]
petallength_label = np.digitize(petallength,bins)
label_map = {1:'small',2:'medium',3:'large',4:np.nan}
petallength_label_re = [label_map[x] for x in petallength_label]
petallength_label_re[-4:]

['large', 'large', 'large', 'large']

In [187]:
iris_2d = np.genfromtxt(url,delimiter=',',dtype='float')
sepallength = iris_2d[:,0]
petallength = iris_2d[:,2]
volums = (np.pi*petallength*(sepallength**2))/3
volums = volums.reshape(len(iris_2d),-1)
np.hstack([iris_2d,volums])

array([[  5.1     ,   3.5     ,   1.4     ,   0.2     ,        nan,
         38.132652],
       [  4.9     ,   3.      ,   1.4     ,   0.2     ,        nan,
         35.200498],
       [  4.7     ,   3.2     ,   1.3     ,   0.2     ,        nan,
         30.072372],
       ...,
       [  6.5     ,   3.      ,   5.2     ,   2.      ,        nan,
        230.069302],
       [  6.2     ,   3.4     ,   5.4     ,   2.3     ,        nan,
        217.373079],
       [  5.9     ,   3.      ,   5.1     ,   1.8     ,        nan,
        185.910028]])

In [189]:
np.unique(species)

array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
      dtype=object)

In [191]:
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
speciese_out = np.random.choice(a,p=[0.5,0.25,0.25])

In [193]:
np.random.seed(100)
probs = np.r_[np.linspace(0,0.5,num=50),np.linspace(0.5,0.75,num=25),np.linspace(0.75,1,num=25)]
index = np.searchsorted(probs,np.random.random(150))
speciese_out=species[index]

In [199]:
b = np.argsort(sepallength)
np.where(b==149)

(array([80]),)

In [200]:
iris = np.genfromtxt(url, delimiter=',', dtype='object')


In [202]:
petal_len_sortosa = iris[iris[:,4]==b'Iris-setosa',[2]].astype('float')
petal_len_sortosa = np.unique(np.sort(petal_len_sortosa))

In [205]:
petal_len_sortosa[-2]

1.7

In [207]:
iris[iris[:,0].argsort()][:20]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'4.9', b'2.5', b'4.5', b'1.7', b'Iris-virginica'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [212]:
petallength = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[2])

val, counts = np.unique(petallength,return_counts=True)
val[np.argmax(counts)]

1.5

In [214]:
petalwidth = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[3])
np.argwhere(petalwidth>1.0)[0]

array([50])

In [216]:
np.random.seed(100)
a = np.random.uniform(1,50,20)
np.clip(a,a_min=10,a_max=30)

array([27.626842, 14.6401  , 21.801362, ..., 10.      , 30.      ,
       14.429614])

In [218]:
np.where(a<10,10,np.where(a>30,30,a))

array([27.626842, 14.6401  , 21.801362, ..., 10.      , 30.      ,
       14.429614])

In [222]:
np.random.seed(100)
a = np.random.uniform(1,50,20)
print(a.argsort())


[ 4 13  5 ...  3 10 15]


In [228]:
np.set_printoptions(threshold=sys.maxsize)
a

array([27.626842, 14.6401  , 21.801362, 42.39403 ,  1.231224,  6.956887,
       33.866705, 41.466785,  7.698623, 29.179573, 44.674776, 11.250904,
       10.081083,  6.310468, 11.765177, 48.952565, 40.772474,  9.42511 ,
       40.995013, 14.429614])

In [229]:
a.argsort()

array([ 4, 13,  5,  8, 17, 12, 11, 14, 19,  1,  2,  0,  9,  6, 16, 18,  7,
        3, 10, 15])

In [232]:
a[np.argpartition(-a,5)[:5]]

array([48.952565, 44.674776, 42.39403 , 41.466785, 40.995013])

In [236]:
np.partition(a,kth=-5)

array([11.250904, 14.429614, 21.801362,  9.42511 ,  1.231224,  6.956887,
       11.765177,  6.310468,  7.698623, 14.6401  , 10.081083, 27.626842,
       40.772474, 33.866705, 29.179573, 40.995013, 41.466785, 42.39403 ,
       44.674776, 48.952565])

In [237]:
np.sort(a)

array([ 1.231224,  6.310468,  6.956887,  7.698623,  9.42511 , 10.081083,
       11.250904, 11.765177, 14.429614, 14.6401  , 21.801362, 27.626842,
       29.179573, 33.866705, 40.772474, 40.995013, 41.466785, 42.39403 ,
       44.674776, 48.952565])