In [2]:
import numpy as np
print(np.__version__)

1.20.3


In [4]:
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [5]:
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [8]:
arr=np.arange(10)
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [12]:
arr_1 = np.arange(10)
arr_1[arr_1%2==1]=-1
arr_1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
arr = np.arange(10)
out = np.where(arr%2==1,-1,arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [17]:
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1,10).reshape(2,-1)
np.vstack([a,b]),np.concatenate([a,b],axis=0),np.r_[a,b]

(array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [25]:
np.hstack([a,b]),np.concatenate([a,b],axis=1),np.c_[a,b]

(array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]),
 array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]]))

In [28]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [39]:
a = np.array([1,2,3,4,5,6,6,7,8,9,9])
b = np.array([7,2,10,2,7,4,9,8])
c = np.intersect1d(a,b)


In [35]:
np.setdiff1d(a,c)

array([1, 3, 5, 6])

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,10])
np.where(a == b)

(array([1, 3, 5, 7]),)

In [46]:
index = np.where((a>=5)&(a<=10))
a[index]

array([5, 6])

In [49]:
index = np.where(np.logical_and(a>=5,a<=10))
a[index]

array([5, 6])

In [51]:
a[(a>=5)&(a<=10)]

array([5, 6])

In [54]:
def maxx(x,y):
    if x>=y:
        return x
    else:
        return y
    
a = np.arange(1,10,2)
b = np.arange(1,20,4)
print(a,b)
pair_max = np.vectorize(maxx,otypes=[float])
pair_max(a,b)


[1 3 5 7 9] [ 1  5  9 13 17]


array([ 1.,  5.,  9., 13., 17.])

In [57]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [61]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [64]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [67]:
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [70]:
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [77]:
np.random.randint(5,10,size=(5,3))+np.random.random((5,3))

array([[7.28710235, 7.56420456, 8.81275296],
       [8.60435264, 8.29209066, 8.80332706],
       [6.9996048 , 8.43685478, 7.44228248],
       [5.4458943 , 6.88663173, 6.24665371],
       [7.17839238, 9.25552805, 6.39575558]])

In [79]:
np.random.uniform(5,10,size=(5,3))


array([[7.19938273, 7.43763482, 9.93625887],
       [6.19699866, 6.51983942, 7.34547726],
       [8.36369635, 9.63285827, 9.24602833],
       [7.63254336, 7.55596454, 7.21924369],
       [7.2711361 , 5.78280897, 5.61187528]])

In [80]:
np.set_printoptions(precision=3)
np.random.uniform(5,10,size=(5,3))

array([[5.646, 6.157, 6.63 ],
       [5.073, 5.517, 9.037],
       [7.43 , 7.318, 9.955],
       [6.464, 7.598, 5.521],
       [9.256, 5.34 , 5.439]])