In [2]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import datasets
iris = datasets.load_iris()
train_x,test_x,train_y,test_y = train_test_split(iris.data,iris.target,random_state=12)
gnb_clf = GaussianNB()
gnb_clf.fit(train_x,train_y)
predict_class = gnb_clf.predict(test_x)
print(accuracy_score(test_y,predict_class))

0.9736842105263158


In [5]:
from sklearn.naive_bayes import MultinomialNB
import numpy as np
X = np.random.randint(5,size=(6,100))
y = np.array([1,2,3,4,5,6])
mnb = MultinomialNB(alpha=1.0,fit_prior=True,class_prior=None)
mnb.fit(X,y)
print(np.exp(mnb.class_log_prior_))
print(mnb.class_count_)
print(mnb.predict(X[[2]]))

[0.16666667 0.16666667 0.16666667 0.16666667 0.16666667 0.16666667]
[1. 1. 1. 1. 1. 1.]
[3]


In [7]:
import numpy as np
from sklearn.naive_bayes import BernoulliNB
x = np.array([[1,2,3,4],[1,3,4,4],[2,4,5,5]])
y = np.array([1,1,2])
bnb = BernoulliNB(alpha=2.0,binarize=3.0,fit_prior=True)
bnb.fit(x,y)
print(bnb.predict(np.array([[1,2,3,4]])))

[1]


In [10]:
print(bnb.class_log_prior_)
print(np.exp(bnb.class_log_prior_))
print(bnb.feature_log_prob_)
print(np.exp(bnb.feature_log_prob_))

[-0.40546511 -1.09861229]
[0.66666667 0.33333333]
[[-1.09861229 -1.09861229 -0.69314718 -0.40546511]
 [-0.91629073 -0.51082562 -0.51082562 -0.51082562]]
[[0.33333333 0.33333333 0.5        0.66666667]
 [0.4        0.6        0.6        0.6       ]]


In [14]:
p_A_c1 = [(0+2)/(2+2*2)*1,
          (0 + 2) / (2 + 2 * 2) * 1,
          (1 + 2) / (2 + 2 * 2) * 1,
          (2 + 2) / (2 + 2 * 2) * 1
          ]
p_A_c2 = [(0 + 2) / (1 + 2 * 2) * 1,
          (1 + 2) / (1 + 2 * 2) * 1,
          (1 + 2) / (1 + 2 * 2) * 1,
          (1 + 2) / (1 + 2 * 2) * 1]

feature_prob = [p_A_c1,p_A_c2]
print(np.array(feature_prob))
print(bnb.class_count_)
print(bnb.feature_count_)

[[0.33333333 0.33333333 0.5        0.66666667]
 [0.4        0.6        0.6        0.6       ]]
[2. 1.]
[[0. 0. 1. 2.]
 [0. 1. 1. 1.]]
